CREATE SCHEMA IF NOT EXISTS jippy_fm;

CREATE TABLE IF NOT EXISTS jippy_fm.status
(
    status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status_name character varying(50),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT status_pkey PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.city
(
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city_name character varying(50),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT city_pkey PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.location
(
    location_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    location_name character varying(50),
    city_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT location_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchants
(
    merchant_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    merchant_name character varying(150),
    merchant_email character varying(150),
    merchant_phone character varying(20),
    merchant_business_type character varying(50),
    status character varying(30) DEFAULT 'PENDING',
	created_at TIMESTAMP,
	created_by integer,
	updated_at TIMESTAMP,
	updated_by integer,
	is_active character varying(1) DEFAULT 'Y',
	is_approved boolean NOT NULL DEFAULT false,
    CONSTRAINT merchants_pkey PRIMARY KEY (merchant_id),
    CONSTRAINT merchant_email UNIQUE (merchant_email),
    CONSTRAINT merchant_phone UNIQUE (merchant_phone)
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchant_kyc
(
    kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    merchant_id bigint NOT NULL,
    pan_number character varying(20),
    aadhaar_number character varying(20),
    fssai_number character varying(30) ,
    verified boolean NOT NULL DEFAULT false,
    created_at TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMP,
    updated_by integer,
    CONSTRAINT merchant_kyc_pkey PRIMARY KEY (kyc_id),
    CONSTRAINT merchant_kyc_merchant_fk_key FOREIGN KEY (merchant_id)
        REFERENCES jippy_fm.merchants (merchant_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.merchant_bank_details
(
    bank_id  integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    recipient_id bigint NOT NULL, -- merchantId,driverId
    account_number character varying(30),
    ifsc_code character varying(15),
    bank_name character varying(100),
    account_holder_name character varying(150),
    user_type character varying(50),
    created_at TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMP,
    updated_by integer,
    CONSTRAINT "merchant_bank_details _pkey" PRIMARY KEY (bank_id),
    CONSTRAINT merchant_id_merchant_fk_key FOREIGN KEY (merchant_id)
        REFERENCES jippy_fm.merchants (merchant_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.employees
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    mobile_number character varying(14),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.permissions
(
    permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    permission_name character varying(100),
    created_by integer,
    created_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.roles
(
    role_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name character varying(100),
    permission_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100),
    password character varying(100),
    role_id integer NOT NULL,
    employee_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    user_type character varying(50),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT "user-role-fk_key" FOREIGN KEY (role_id)
        REFERENCES jippy_fm.roles (role_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
     CONSTRAINT "user-employee-fk_key" FOREIGN KEY (employee_id)
            REFERENCES jippy_fm.employees (employee_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);



CREATE TABLE IF NOT EXISTS jippy_fm.approval_types
(
    approval_requests_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    approval_requests_name character varying(100) NOT NULL, --outlet approval,merchant approval,
    created_by integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT approval_requests_pkey PRIMARY KEY (approval_requests_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.approvals
(
    approvals_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    approval_type integer NOT NULL,
    entity_id integer NOT NULL,
    status character varying(20) NOT NULL,
    rejected_reason character varying(500),
    approved_by integer,
    approved_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT approvals_pkey PRIMARY KEY (approvals_id),
    CONSTRAINT approval_status_fk_key FOREIGN KEY (status)
        REFERENCES jippy_fm.status (status_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT approval_type_fk_key FOREIGN KEY (approval_type)
        REFERENCES jippy_fm.approval_types (approval_requests_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.business_approvers(
    business_approver_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application character varying(100) NOT NULL, --food,mart,driver
    application_module character varying(100) NOT NULL, --food and mart(outlet,merchant,deals)--driver(subscription,driver kyc)
    city_id integer,
    fleet_manager_id integer,
    operation_manager_id integer,
    super_admin_id integer,
    fleet_duration integer,
    operation_manager_duration integer,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT business_approvers_pkey PRIMARY KEY (business_approver_id),
     CONSTRAINT business_approvers_approval_type_fk_key FOREIGN KEY (approval_type)
            REFERENCES jippy_fm.approval_types (approval_requests_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);




CREATE TABLE jippy_fm.zones (
    zone_id SERIAL PRIMARY KEY,
    zone_name VARCHAR(100),
    boundary GEOGRAPHY(POLYGON, 4326),
	city VARCHAR(100),
	state VARCHAR(100),
	created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlets
(
    outlet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_name character varying(100) NOT NULL,
    merchant_id integer NOT NULL,
    cuisine_type character varying(100) NOT NULL,
    outlet_phone character varying(20) NOT NULL,
    radius NUMERIC(10, 2) NOT NULL DEFAULT 3.00,
    boundary GEOGRAPHY(POLYGON, 4326),
    oulet_location GEOGRAPHY(POINT, 4326),
    review NUMERIC(2, 1),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    is_active character varying(1) DEFAULT 'Y',
    employee_id integer,
    is_approved boolean NOT NULL DEFAULT false,
    CONSTRAINT outlets_pkey PRIMARY KEY (outlet_id),
    CONSTRAINT outlet_merchant_fk_key FOREIGN KEY (merchant_id)
        REFERENCES jippy_fm.merchants (merchant_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.address
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    jippy_address_id integer NOT NULL, --outletId,merchantId
    building_number  character varying(50) NOT NULL,
    road  character varying(100) NOT NULL,
    landmark  character varying(150) NOT NULL,
    city_id integer NOT NULL,
    state  character varying(100) NOT NULL,
    pincode  character varying(6) NOT NULL,
    addresss_type character varying(50) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_address_pkey PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.days_of_week
(
    day_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_name character varying(20) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT days_of_week_pkey PRIMARY KEY (day_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_days(
    outlet_day_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    is_open boolean NOT NULL DEFAULT true,
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_days_pkey PRIMARY KEY (outlet_day_id),
    CONSTRAINT outlet_days_outlet_fk_key FOREIGN KEY (outlet_id)
        REFERENCES jippy_fm.outlets (outlet_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_fm.categories
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name character varying(100) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.outlet_categories
(
    outlet_category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
	--is_available boolean,
    category_id integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_categories_pkey PRIMARY KEY (outlet_category_id),
     CONSTRAINT outlet_categories_fk_key FOREIGN KEY (outlet_id)
            REFERENCES jippy_fm.outlets (outlet_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT outlet_category_category_fk_key FOREIGN KEY (category_id)
             REFERENCES jippy_fm.categories (category_id)
             ON UPDATE NO ACTION
             ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.products
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_category_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    description character varying(500) NOT NULL,
    merchant_price NUMERIC(10, 2) NOT NULL,
    is_veg  boolean NOT NULL DEFAULT true,
    has_product_variants boolean NOT NULL DEFAULT false,
    -- is_available boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
     CONSTRAINT product_outlet_categories_fk_key FOREIGN KEY (outlet_category_id)
                 REFERENCES jippy_fm.outlet_categories (outlet_category_id)
                 ON UPDATE NO ACTION
                 ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_variants
(
    product_variant_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    variant_name character varying(100) NOT NULL,
    merchant_price NUMERIC(10, 2) NOT NULL,
    -- is_available boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_variants_pkey PRIMARY KEY (product_variant_id),
     CONSTRAINT product_variants_fk_key FOREIGN KEY (product_id)
            REFERENCES jippy_fm.products (product_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_fm.master_products(
    master_product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    master_product_name character varying(100) NOT NULL,
    description TEXT,
    short_description TEXT,
    photo TEXT,
    photos text,
    thumbnail TEXT,
    veg integer NOT NULL DEFAULT 0,
    non_veg integer NOT NULL DEFAULT 0,
    food_type character varying(50),
    -- cuisine_type character varying(100),
    calories integer DEFAULT 0,
    protein integer DEFAULT 0,
    fats integer DEFAULT 0,
    carbs integer DEFAULT 0,
    grams integer DEFAULT 0,
    --tags text,
    --display_order integer,
    -- is_available integer NOT NULL DEFAULT 0,
    publish integer NOT NULL DEFAULT 1,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT master_products_pkey PRIMARY KEY (master_product_id)
);

CREATE TABLE IF NOT EXISTS jippy_fm.product_available_timings(
    product_available_timing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_available_timings_pkey PRIMARY KEY (product_available_timing_id),
     CONSTRAINT product_available_timings_product_fk_key FOREIGN KEY (product_id)
            REFERENCES jippy_fm.products (product_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


