CREATE SCHEMA IF NOT EXISTS jippy_notification;

CREATE TABLE  IF NOT EXISTS jippy_notification.notifications(
    notification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role character varying(100) NOT NULL, -- outlet,driver,admin,customer
    subject character varying(100) NOT NULL, -- order notification,
    message character varying(100) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);


CREATE TABLE IF NOT EXISTS jippy_notification.notification_recipients(
    notification_recipient_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    notification_id integer NOT NULL,
    recipient_id integer NOT NULL, -- can be outlet_id, driver_id, customer_id based on role in notifications table
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT notification_recipients_pkey PRIMARY KEY (notification_recipient_id),
     CONSTRAINT notification_recipients_notification_fk_key FOREIGN KEY (notification_id)
            REFERENCES jippy_notification.notifications (notification_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_notification_status(
    order_notification_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id character varying(30) NOT NULL,
    notification_id integer NOT NULL, -- placed, delivered, cancelled
    notification_status boolean DEFAULT false, -- false means notification is not sent, true means notification is sent
    changed_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_notification_status_pkey PRIMARY KEY (order_notification_status_id),
    CONSTRAINT order_notification_status_notification_fk_key FOREIGN KEY (notification_id)
                REFERENCES jippy_notification.notifications (notification_id)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
    );


INSERT INTO jippy_notification.notifications(
	notification_id, role, subject, message, created_at, created_by)
	VALUES (1, 'OUTLET', 'NEW ORDER NOTIFICATION', 'NEW ORDER IS WAITING FOR YOUR CONFIRMATION', now(), 1);
