server:
  port: 8082
spring:
  application:
    name: customerandorder
  datasource:
    # Syntax: ${VARIABLE_NAME:DEFAULT_VALUE}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/co_db}
    username: ${SPRING_DATASOURCE_USERNAME:co_user}
    password: ${SPRING_DATASOURCE_PASSWORD:co_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

    #  Kafka Producer Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Serializes the Message Key (Order ID) as a String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Serializes the OrderEvent object into a JSON string
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      # Ensures the message is acknowledged by Kafka brokers
      acks: all

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
