server:
  port: 8082
spring:
  application:
    name: customerandorder
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: jippy_customer_and_order
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

    #  Kafka Producer Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Serializes the Message Key (Order ID) as a String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Serializes the OrderEvent object into a JSON string
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      # Ensures the message is acknowledged by Kafka brokers
      acks: all

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/