CREATE SCHEMA IF NOT EXISTS jippy_customer_and_order;

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.application_versions(
    version_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_type character varying(50) NOT NULL, -- customer_app, outlet_app, driver_app
    version_number character varying(20) NOT NULL,--v1,v2,v3
    api_url character varying(100),
    api_version character varying(20),
    api_functionality character varying(100),
    db_query TEXT,
    db_query_version character varying(20),
    is_active BOOLEAN,
    is_approved BOOLEAN,
    environment character varying(20) NOT NULL, -- production, testing,development
    created_at timestamp without time zone,
    created_by integer
    CONSTRAINT application_versions_pkey PRIMARY KEY (version_id),
    CONSTRAINT application_version_unique UNIQUE (application_type, version_number)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_status(
    customer_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,)
    status_name character varying(20) NOT NULL, -- new,existing_coupons_applied,
    --existing_coupons_not_applied,existing_order_count
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_status_pkey PRIMARY KEY (customer_status_id),
    CONSTRAINT status_name UNIQUE (status_name)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer(
customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    phone_number character varying(15),
    customer_status_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
    CONSTRAINT email UNIQUE (email)
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_delivery_addresses(
    customer_address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    location GEOGRAPHY(POINT),
    door_no character varying(30),
    building_name character varying(30),
    lane_no character varying(30),
    area integer,
    city integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_address_pkey PRIMARY KEY (customer_address_id),

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_cart(
    cart_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    total_price NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_cart_pkey PRIMARY KEY (cart_id),
    CONSTRAINT customer_cart_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_coupons(
    customer_coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    coupon_id integer NOT NULL,
    order_id integer,
    is_redeemed BOOLEAN DEFAULT FALSE,
    redeemed_at timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_coupons_pkey PRIMARY KEY (customer_coupon_id),
    CONSTRAINT customer_coupons_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_points_history(
    points_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    points integer NOT NULL,
    points_source character varying(50) NOT NULL, -- company_points, referral_points, daily_streaks, deals
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT points_transaction_pkey PRIMARY KEY (points_transaction_id),
    CONSTRAINT points_transaction_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_wallet(
    wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    total_earned_points integer DEFAULT 0,
    total_earn_amount NUMERIC(10, 2) DEFAULT 0, -- minimum 1000 points
    returned_points integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_wallet_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT customer_wallet_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.customer_streaks(
    customer_streak_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    check_in_date date NOT NULL,
    current_streak integer DEFAULT 0, -- every day when logged in the value gets incremented by 1, if there is a break in the streak then it will be reset to 0 and start from first
    max_streak integer DEFAULT 0, -- stores max streak achieved by user, if current streak is greater than max streak then update the max streak with current streak value
    points integer DEFAULT 0,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT user_streaks_pkey PRIMARY KEY (user_streak_id),
    CONSTRAINT customer_last_login UNIQUE (last_login_date,customer_id),
    CONSTRAINT user_streaks_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);



-- online price of selected products - merchant price on selected products in order-platform fee-delivery charges-gst = balance;
-- we will generate 2 coupons that is equal to balance(coupon should be applicable on coupon available restaurants);
-- if order is getting delayed by any reason beyond the estimated time, then increase estimated delivery time by adding current delivery time+half of current delivery time.
-- incase of driver reaching before deliver time to the customer, then we need to inform customer as we reached before estimated delivery time
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.orders(
    order_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    outlet_id integer NOT NULL,
    driver_id integer,
    order_status character varying(20) NOT NULL, -- placed, delivered, cancelled
    delivery_address character varying(500) NOT NULL,
    customer_phone_number character varying(15) NOT NULL,
    preparation_time timestamp without time zone,
    estimated_delivery_time timestamp without time zone,
    distance_kms NUMERIC (10,2),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT orders_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.order_items(
    order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    merchant_unit_price NUMERIC(10, 2) NOT NULL,
    online_unit_price NUMERIC(10, 2) NOT NULL,
    online_price_total NUMERIC(10, 2) NOT NULL,
    merchant_price_total NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT order_items_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customer_and_order.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
);

 CREATE TABLE if not exists jippy_customer_and_order.order_price_breakup(
    order_price_breakup_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    coupon_id integer,
    order_amount NUMERIC(10, 2) NOT NULL,
    platform_fee NUMERIC(10, 2),
    delivery_fee NUMERIC(10, 2),
    surge_fee NUMERIC(10, 2),
    packaging_fee NUMERIC(10, 2),
     gst NUMERIC(10, 2),
     order_total_amount NUMERIC(10, 2) NOT NULL,
   coupon_discount NUMERIC(10, 2) DEFAULT 0,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_price_breakup_pkey PRIMARY KEY (order_price_breakup_id),
     CONSTRAINT order_price_breakup_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customer_and_order.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE  IF NOT EXISTS jippy_customer_and_order.notifications(
    notification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role character varying(100) NOT NULL, -- outlet,driver,admin,customer
    subject character varying(100) NOT NULL, -- order notification,
    message character varying(100) NOT NULL,
    createdAt timestamp without time zone,
    createdBy integer,
    updatedAt timestamp without time zone,
    updatedBy integer,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);


CREATE TABLE IF NOT EXISTS jippy_customer_and_order.notification_recipients(
    notification_recipient_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    notification_id integer NOT NULL,
    recipient_id integer NOT NULL, -- can be outlet_id, driver_id, customer_id based on role in notifications table
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT notification_recipients_pkey PRIMARY KEY (notification_recipient_id),
     CONSTRAINT notification_recipients_notificsation_fk_key FOREIGN KEY (notification_id)
            REFERENCES jippy_customer_and_order.notifications (notification_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver(
    driver_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone_number character varying(15) NOT NULL,
    email character varying(100),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_pkey PRIMARY KEY (driver_id)

);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_kyc(
    driver_kyc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    aadhar_number character varying(20) NOT NULL,
    driving_license_number character varying(20) NOT NULL,
    rc_copy character varying(100) NOT NULL,
    created_by integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_kyc_pkey PRIMARY KEY (driver_kyc_id),
     CONSTRAINT driver_kyc_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_delivery_charge_settings(
    delivery_charge_setting_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pick_up_kms_range_from NUMERIC(10,2) NOT NULL,
     pick_up_kms_range_to NUMERIC(10,2) NOT NULL,
    unit_price_per_pick_km NUMERIC(10, 2) NOT NULL,
    delivery_kms_range_from NUMERIC(10, 2) NOT NULL,
    delivery_kms_range_to NUMERIC(10, 2) NOT NULL,
    unit_price_per_deliver_km NUMERIC(10, 2) NOT NULL,
    num_of_orders integer NOT NULL,
    incentives_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_delivery_charge_settings_pkey PRIMARY KEY (delivery_charge_setting_id)
);
-- Track driver attendence daily
-- Fleet manager can track driver history.
-- Driver can not deliver orders though they are available, then we have to stop incentives.
--Driver settlements can be done in weekly 2 times, but incentives are done monthly once.
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_history(
    driver_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    no_of_orders integer NOT NULL,
    last_login_date timestamp without time zone,
    available_from_time timestamp without time zone,
    available_to_time timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_history_pkey PRIMARY KEY (driver_history_id),
     CONSTRAINT driver_history_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS.jippy_customer_and_order.driver_wallet(
    wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    total_cod_amount NUMERIC(10, 2) DEFAULT 0,-- if cod amount >=1000 then driver will not receive orders, driver needs to pay taht 1000rs to company account. Fleet manager can release the orders lock.
    orders_lock BOOLEAN DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_wallet_pkey PRIMARY KEY (wallet_id),
     CONSTRAINT driver_wallet_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

-- if same customere placed 2 orders within 3kms from different outlets, then can we assign 2 orders to same driver.
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_current_location(
    driver_location_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    current_location GEOGRAPHY(POINT, 4326), -- stores latitude and longitude of driver location
    is_available BOOLEAN, -- if driver is available to receive orders or not
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_location_pkey PRIMARY KEY (location_id),
     CONSTRAINT driver_location_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE INDEX idx_driver_current_location
ON jippy_customer_and_order.driver_current_location USING GIST (current_location);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_attendance_logs (
    driver_attendance_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    status character varying(20) NOT NULL, -- online, offline
    changed_at timestamp without time zone NOT NULL,
    location GEOGRAPHY(POINT),   -- Where they were when they went online
    device_id TEXT,
    created_by integer,
    updated_at timestamp without time zone,
    CONSTRAINT driver_attendance_logs_pkey PRIMARY KEY (log_id),
     CONSTRAINT driver_attendance_logs_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.driver_stats(
    driver_stats_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,)
    driver_id integer NOT NULL,
    work_date DATE DEFAULT CURRENT_DATE,
    first_online timestamp without time zone,
    last_offline timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_stats_pkey PRIMARY KEY (driver_stats_id),
     CONSTRAINT driver_stats_driver_fk_key FOREIGN KEY (driver_id)
            REFERENCES jippy_customer_and_order.driver (driver_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

-- 2. Daily Summary for fast reporting
CREATE TABLE driver_daily_stats (
    driver_id INTEGER,
    work_date DATE DEFAULT CURRENT_DATE,
    first_online TIMESTAMP WITH TIME ZONE,
    last_offline TIMESTAMP WITH TIME ZONE,
    total_minutes_online INTEGER DEFAULT 0,
    PRIMARY KEY (driver_id, work_date)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.reason_settings(
    reason_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_type character varying(50) NOT NULL, -- driver, outlet, customer
    reason_type character varying(50) NOT NULL, -- incentives hold, order cancellation,
    reason_text TEXT NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT reason_settings_pkey PRIMARY KEY (reason_id),
    CONSTRAINT reason_type UNIQUE (reason_type)
);


--- wallet system
-- companies point (ex: direct give 1750 points to customer- on every order 10% points can re redeemed)
--  referral points (ex: refer a friend and get 1000 points - on every order 10% points can re redeemed, refereed customer should place the order then only points will get)
-- daily streaks( daily login can be tracked, 25 points per day up to 30 days continuously, if it has a break in the middle, do it as 0 and start from first)
-- deals
CREATE TABLE IF NOT EXISTS jippy_customer_and_order.admin_streak_settings(
    streak_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    streak_source character varying(50) NOT NULL, --daily_login, referral, company_points,
    points_per_day integer,
    point_settings NOT NULL,
    max_streak_days integer,
    is_active boolean DEFAULT false,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT admin_streak_settings_pkey PRIMARY KEY (streak_settings_id),
    CONSTRAINT streak_type UNIQUE (streak_type)
);

CREATE TABLE IF NOT EXISTS jippy_customer_and_order.referrals(
    referral_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    referrer_customer_id integer NOT NULL,
    referee_customer_id integer NOT NULL,
    referral_code character varying(20) NOT NULL,
    referral_status character varying(20) NOT NULL DEFAULT 'PENDING', -- pending, qualified,rewarded
    referral_type character varying(50) NOT NULL, -- customer,driver.
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT referral_program_pkey PRIMARY KEY (referral_id),
    CONSTRAINT referral_program_referrer_fk_key FOREIGN KEY (referrer_customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT referral_program_referee_fk_key FOREIGN KEY (referee_customer_id)
            REFERENCES jippy_customer_and_order.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


