server:
    port: 8081
spring:
  application:
    name: division
 datasource:
    # Syntax: ${VARIABLE_NAME:DEFAULT_VALUE}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/div_db}
    username: ${SPRING_DATASOURCE_USERNAME:div_user}
    password: ${SPRING_DATASOURCE_PASSWORD:div_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true



