CREATE SCHEMA IF NOT EXISTS jippy_division;

CREATE TABLE IF NOT EXISTS jippy_division.price_model
(
    price_model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_model_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT price_model_pkey PRIMARY KEY (price_model_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.product_online_pricing
(
    product_online_pricing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    base_price NUMERIC(10, 2) NOT NULL,
    price_model_id integer,
    price_model_value NUMERIC(10, 2),
    final_price NUMERIC(10, 2) NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_online_pricing_pkey PRIMARY KEY (product_online_pricing_id),
     CONSTRAINT online_pricing_price_model_type_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_fm.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_division.coupons (
   coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_code character varying(100)  NOT NULL,
   price_model_id integer,
   value NUMERIC(10,2),
   max_discount NUMERIC(10,2),
   is_active BOOLEAN DEFAULT TRUE,
   start_time timestamp without time zone,
   end_time timestamp without time zone,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id),
    CONSTRAINT coupon_code UNIQUE (coupon_code),
    CONSTRAINT coupons_price_model_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_division.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.coupon_mapping (
   coupon_mapping_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_id integer  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer NOT NULL,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupon_mapping_pkey PRIMARY KEY (coupon_mapping_id),
    CONSTRAINT coupon_mapping_coupons_fk_key FOREIGN KEY (coupon_id)
            REFERENCES jippy_division.coupons (coupon_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);