CREATE SCHEMA IF NOT EXISTS jippy_division;

CREATE TABLE IF NOT EXISTS jippy_division.price_model
(
    price_model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_model_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT price_model_pkey PRIMARY KEY (price_model_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.application_type
(
    application_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT application_type_pkey PRIMARY KEY (application_type_id)
);

-- flat,percentage,birthday, happyHours,autocoupon,firstTimeLogin



CREATE TABLE IF NOT EXISTS jippy_division.coupons (
   coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_code character varying(100)  NOT NULL,
   price_model_id integer,
   application_type integer,
   min_order_value NUMERIC(10,2),
   discount_value NUMERIC(10,2),
   payment_method integer,
   usage_limit_per_user integer,
   is_active BOOLEAN DEFAULT FALSE,
   start_time timestamp without time zone,
   end_time timestamp without time zone,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id),
    CONSTRAINT coupons_price_model_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_division.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.promotion_date_time(
promotion_date_time_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
promotion_date timestamp without time zone,
promotion_from_time timestamp without time zone,
promotion_to_time timestamp without time zone,
created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT promotion_date_time_pkey PRIMARY KEY (promotion_date_time_id),
);


CREATE TABLE IF NOT EXISTS jippy_division.coupon_mapping_outlets_products (
   coupon_mapping_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_id integer  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer NOT NULL,
   area_id integer NOT NULL,
   promotion_date_time_id integer,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupon_mapping_pkey PRIMARY KEY (coupon_mapping_id),
    CONSTRAINT coupon_mapping_coupons_fk_key FOREIGN KEY (coupon_id)
            REFERENCES jippy_division.coupons (coupon_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.price_drop (
   price_drop_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   price_drop_value NUMERIC(10,2)  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer NOT NULL,
   area_id integer NOT NULL,
   promotion_date_time_id integer,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT price_drop_pkey PRIMARY KEY (price_drop_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.driver_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    settlement_amount NUMERIC(10, 2) NOT NULL,
    settlement_status character varying(100), -- pending, completed, failed
    settlement_from_date timestamp without time zone,
    settlement_to_date timestamp without time zone,
    reason TEXT,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_settlement_pkey PRIMARY KEY (settlement_id)
);


CREATE TABLE IF NOT EXISTS jippy_division.driver_incentives_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    driver_id integer NOT NULL,
    incentives_amount NUMERIC(10, 2) NOT NULL,
    settlement_date timestamp without time zone,
    settlement_status character varying(100), -- pending, completed, failed
    reason TEXT,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT driver_incentives_settlement_pkey PRIMARY KEY (settlement_id)
);



CREATE TABLE IF NOT EXISTS jippy_division.payment(
    payment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    payment_method character varying(20) NOT NULL, -- online, cod
    payment_gateway character varying(50), -- razorpay,gpay,phonepe, wallet
    payment_status character varying(20) NOT NULL, -- pending, completed, failed
    gateway_charges NUMERIC(10, 2),
    amount_paid NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT payment_pkey PRIMARY KEY (payment_id),
     CONSTRAINT payment_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customerAndOrder.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.outlet_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    order_id integer NOT NULL,
    settlement_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_settlement_pkey PRIMARY KEY (settlement_id)
);

CREATE TABLE IF NOT EXISTS jippy_division.outlet_weekly_settlement(
    weekly_settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    week_start_date date NOT NULL,
    week_end_date date NOT NULL,
    total_settlement_amount NUMERIC(10, 2) NOT NULL,
    payment_status character varying(20) NOT NULL, -- pending, completed, payment_failed
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_weekly_settlement_pkey PRIMARY KEY (weekly_settlement_id)
);

