CREATE SCHEMA IF NOT EXISTS jippy_division;

CREATE TABLE IF NOT EXISTS jippy_division.price_model
(
    price_model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    price_model_name character varying(20),
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT price_model_pkey PRIMARY KEY (price_model_id)
);
-- flat,percentage,birthday, happyHours,autocoupon,firstTimeLogin

CREATE TABLE IF NOT EXISTS jippy_division.product_online_pricing
(
    product_online_pricing_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id integer NOT NULL,
    outlet_price NUMERIC(10, 2) NOT NULL,
    online_price NUMERIC(10, 2) NOT NULL,
    price_model_id integer,
    price_model_value NUMERIC(10, 2),
    final_price NUMERIC(10, 2) NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT product_online_pricing_pkey PRIMARY KEY (product_online_pricing_id),
     CONSTRAINT online_pricing_price_model_type_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_fm.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

CREATE TABLE IF NOT EXISTS jippy_division.coupons (
   coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_code character varying(100)  NOT NULL,
   price_model_id integer,
   value NUMERIC(10,2),
   max_discount NUMERIC(10,2),
   is_active BOOLEAN DEFAULT TRUE,
   start_time timestamp without time zone,
   end_time timestamp without time zone,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id),
    CONSTRAINT coupon_code UNIQUE (coupon_code),
    CONSTRAINT coupons_price_model_fk_key FOREIGN KEY (price_model_id)
            REFERENCES jippy_division.price_model (price_model_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_division.coupon_mapping_outlets_products (
   coupon_mapping_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   coupon_id integer  NOT NULL,
   outlet_id integer NOT NULL,
   product_id integer NOT NULL,
   created_at timestamp without time zone,
   created_by integer,
   updated_at timestamp without time zone,
   updated_by integer,
    CONSTRAINT coupon_mapping_pkey PRIMARY KEY (coupon_mapping_id),
    CONSTRAINT coupon_mapping_coupons_fk_key FOREIGN KEY (coupon_id)
            REFERENCES jippy_division.coupons (coupon_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.customer_status(
    customer_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,)
    status_name character varying(20) NOT NULL, -- new,existing_coupons_applied,
    --existing_coupons_not_applied,existing_order_count
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_status_pkey PRIMARY KEY (customer_status_id),
    CONSTRAINT status_name UNIQUE (status_name)
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.customer(
customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    phone_number character varying(15),
    customer_status_id integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
    CONSTRAINT email UNIQUE (email)
);
-- online price of selected products - merchant price on selected products in order-platform fee-delivery charges-gst = balance;
-- we will generate 2 coupons that is equal to balance(coupon should be applicable on coupon available restaurants);
CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.orders(
    order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    outlet_id integer NOT NULL,
    driver_id integer,
    order_status character varying(20) NOT NULL, -- placed, delivered, cancelled
    delivery_address character varying(500) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT orders_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.order_items(
    order_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    merchant_unit_price NUMERIC(10, 2) NOT NULL,
    online_unit_price NUMERIC(10, 2) NOT NULL,
    online_price_total NUMERIC(10, 2) NOT NULL,
    merchant_price_total NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT order_items_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customerAndOrder.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
);

 CREATE TABLE if not exists jippy_customerAndOrder.order_price_breakup(
    order_price_breakup_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    coupon_id integer,
    order_total_amount NUMERIC(10, 2) NOT NULL,
    platform_fee NUMERIC(10, 2),
    delivery_fee NUMERIC(10, 2),
    surge_fee NUMERIC(10, 2),
    packaging_fee NUMERIC(10, 2),
     gst NUMERIC(10, 2),
     order_total NUMERIC(10, 2) NOT NULL,
   coupon_discount NUMERIC(10, 2) DEFAULT 0,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT order_price_breakup_pkey PRIMARY KEY (order_price_breakup_id),
     CONSTRAINT order_price_breakup_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customerAndOrder.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.payment(
    payment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    payment_method character varying(20) NOT NULL, -- online, cod
    payment_gateway character varying(50), -- razorpay,gpay,phonepe, wallet
    payment_status character varying(20) NOT NULL, -- pending, completed, failed
    amount_paid NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT payment_pkey PRIMARY KEY (payment_id),
     CONSTRAINT payment_order_fk_key FOREIGN KEY (order_id)
            REFERENCES jippy_customerAndOrder.orders (order_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.outlet_settlement(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    order_id integer NOT NULL,
    settlement_amount NUMERIC(10, 2) NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_settlement_pkey PRIMARY KEY (settlement_id)
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.outlet_weekly_settlement(
    weekly_settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    week_start_date date NOT NULL,
    week_end_date date NOT NULL,
    total_settlement_amount NUMERIC(10, 2) NOT NULL,
    payment_status character varying(20) NOT NULL, -- pending, completed, payment_failed
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT outlet_weekly_settlement_pkey PRIMARY KEY (weekly_settlement_id)
);



CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.customer_coupons(
    customer_coupon_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    coupon_id integer NOT NULL,
    order_id integer,
    is_redeemed BOOLEAN DEFAULT FALSE,
    redeemed_at timestamp without time zone,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_coupons_pkey PRIMARY KEY (customer_coupon_id),
    CONSTRAINT customer_coupons_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT customer_coupons_coupons_fk_key FOREIGN KEY (coupon_id)
            REFERENCES jippy_division.coupons (coupon_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION

);

--- wallet system
-- companies point (ex: direct give 1750 points to customer- on every order 10% points can re redeemed)
--  referral points (ex: refer a friend and get 1000 points - on every order 10% points can re redeemed, refereed customer should place the order then only points will get)
-- daily streaks( daily login can be tracked, 25 points per day up to 30 days continuously, if it has a break in the middle, do it as 0 and start from first)
-- deals
CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.admin_streak_settings(
    streak_settings_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    streak_source character varying(50) NOT NULL, --daily_login, referral, company_points,
    points_per_day integer NOT NULL,
    point_settings NOT NULL,
    max_streak_days integer NOT NULL,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT admin_streak_settings_pkey PRIMARY KEY (streak_settings_id),
    CONSTRAINT streak_type UNIQUE (streak_type)
);


CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.users_streaks(
    user_streak_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    check_in_date date NOT NULL,
    current_streak integer DEFAULT 0, -- every day when logged in the value gets incremented by 1, if there is a break in the streak then it will be reset to 0 and start from first
    max_streak integer DEFAULT 0, -- stores max streak achieved by user, if current streak is greater than max streak then update the max streak with current streak value
    points integer DEFAULT 0,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT user_streaks_pkey PRIMARY KEY (user_streak_id),
    CONSTRAINT customer_last_login UNIQUE (last_login_date,customer_id),
    CONSTRAINT user_streaks_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.customer_points_history(
    points_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    points integer NOT NULL,
    points_source character varying(50) NOT NULL, -- company_points, referral_points, daily_streaks, deals
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT points_transaction_pkey PRIMARY KEY (points_transaction_id),
    CONSTRAINT points_transaction_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.customer_wallet(
    wallet_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NOT NULL,
    total_earned_points integer DEFAULT 0,
    total_earn_amount NUMERIC(10, 2) DEFAULT 0, -- minimum 1000 points
    returned_points integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT customer_wallet_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT customer_wallet_customer_fk_key FOREIGN KEY (customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS jippy_customerAndOrder.referrals(
    referral_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    referrer_customer_id integer NOT NULL,
    referee_customer_id integer NOT NULL,
    referral_code character varying(20) NOT NULL,
    referral_status character varying(20) NOT NULL DEFAULT 'PENDING', -- pending, qualified,rewarded
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT referral_program_pkey PRIMARY KEY (referral_id),
    CONSTRAINT referral_program_referrer_fk_key FOREIGN KEY (referrer_customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
     CONSTRAINT referral_program_referee_fk_key FOREIGN KEY (referee_customer_id)
            REFERENCES jippy_customerAndOrder.customer (customer_id)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);
